name: ingrid
favicon: null
layout_spectrum: 0.030515799997374415
typography_spectrum: 0.2180171071086079
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5902148385066539
  lightness: 0.5455768296960741
  saturation: 0.6586558450944722
  rhythmicContrast: 0.5308065712451935
purpose: []
